src/idpay/30_apim_diagnostics.tf
=> fix: pre commit execution

src/idpay/00_data.tf, src/idpay/20_apim_api_token_exchange_register.tf, src/idpay/99_locals.tf, src/idpay/apim/api/idpay_token_exchange/jwt_exchange_register.xml.tpl, src/idpay/apim/api/idpay_token_exchange/jwt_register_token_test.xml.tpl
=> chore: [RDB-9] added token exchange api and policy for asset register

src/idpay/20_apim_api_register.tf, src/idpay/apim/api/idpay_asset_register/role-permission/consent-policy.xml.tpl, src/idpay/apim/api/idpay_asset_register/role-permission/get-permission-policy.xml.tpl, src/idpay/apim/api/idpay_asset_register/role-permission/openapi.role-permission.yml, src/idpay/apim/api_product/portal_register/policy_portal.xml.tpl
=> chore: Asset register role-permission api

src/idpay/00_data.tf, src/idpay/20_apim_api_register.tf, src/idpay/20_apim_api_token_exchange_register.tf, src/idpay/99_variables.tf, src/idpay/apim/api/idpay_asset_register/register/download-report.xml.tpl, src/idpay/apim/api/idpay_asset_register/register/get-download-report.xml.tpl, src/idpay/apim/api/idpay_asset_register/register/openapi.register.yml, src/idpay/apim/api/idpay_asset_register/register/post-upload-csv.xml.tpl, src/idpay/apim/api/idpay_asset_register/register/upload-csv.xml.tpl, src/idpay/apim/api/idpay_asset_register/role-permission/openapi.role-permission.yml, src/idpay/apim/api/idpay_token_exchange/jwt_exchange_register.xml.tpl, src/idpay/apim/api_product/portal_register/policy_portal.xml.tpl, src/idpay/env/itn-dev/terraform.tfvars
=> chore: [RDB-38] asset register csv api

src/idpay/20_apim_api_register.tf, src/idpay/apim/api/idpay_asset_register/get-institution.xml.tpl, src/idpay/apim/api/idpay_asset_register/get-institutions.xml.tpl, src/idpay/apim/api/idpay_asset_register/get-product-files-batch-name.xml.tpl, src/idpay/apim/api/idpay_asset_register/get-products.xml.tpl, src/idpay/apim/api/idpay_asset_register/openapi.register.yml, src/idpay/apim/api/idpay_asset_register/post-product-files-verify.xml.tpl, src/idpay/apim/api_product/portal_register/policy_portal.xml.tpl
Ass APIs for product details and Invitalia users (list of producers)
Add Invitalia API to enhancethe asset register
---
=> feat: RDB-62 api batch name

src/idpay/apim/api/idpay_asset_register/get-institution.xml.tpl, src/idpay/apim/api/idpay_asset_register/get-institutions.xml.tpl, src/idpay/apim/api/idpay_token_exchange/jwt_exchange_register.xml.tpl
=> fix:  replace na value

src/idpay/apim/api/idpay_merchant/openapi.merchant.yml, src/idpay/apim/api/idpay_merchants_portal/openapi.merchants.portal.yml
Added new Iban and ibanHolder PATCH API in merchant.
This implementation is required in order to develop the new modal that saves IBAN and IBAN's holder.
---
=> feat: [EBE-28] New Iban PATCH API in merchant

.github/workflows/static_analysis_pr.yml, src/idpay/20_apim_api_acquirer.tf, src/idpay/20_apim_api_mock.tf, src/idpay/env/itn-prod/terraform.tfvars
- Removed unused `subscriptions_limit` configuration from API Acquirer.
- Enabled conditional mock API provisioning based on feature flags.
- Added Token Exchange configuration.
This change removes redundant configurations to streamline the codebase and introduces feature-flag-based API provisioning for better flexibility and dynamic behavior. Additionally, Token Exchange configuration is added for upcoming functionality.
This update aims to improve maintainability and prepare for future enhancements through dynamic provisioning and additional configurations.
---
=> feat: [IDP-2765] Idpay aspi spec first deploy

src/idpay/apim/api/idpay_asset_register/openapi.register.yml
=> fix: swagger update

.spectral.yaml, src/idpay/apim/api/idpay_appio_full/openapi.appio.full.yml, src/idpay/apim/api/idpay_iban/openapi.iban.yml, src/idpay/apim/api/idpay_iban/openapi.iban.yml.tpl, src/idpay/apim/api/idpay_onboarding_workflow/openapi.onboarding.yml, src/idpay/apim/api/idpay_onboarding_workflow/openapi.onboarding.yml.tpl, src/idpay/apim/api/idpay_payment_io/openapi.payment_io.yml.tpl, src/idpay/apim/api/idpay_qrcode_payment/io/openapi.qrcode_payment_io.yml.tpl, src/idpay/apim/api/idpay_timeline/openapi.timeline.yml.tpl, src/idpay/apim/api/idpay_wallet/openapi.wallet.yml.tpl
- Add single PUT API for onboarding
- Remove APIs for onboarding by steps
- Add API for Initiative details
- Remove validation in response object
- Update swagger for appio full
Provide app io full swagger updated with new APIs for onboarding
---
=> feat: Update swagger appio full

.devops/idpay-code-review-pipelines.yml, .devops/idpay-deploy-pipelines.yml, .devops/mcshared-code-review-pipelines.yml, .devops/mcshared-deploy-pipelines.yml, .devops/srtp-code-review-pipelines.yml, .devops/srtp-deploy-pipelines.yml, README.md
=> feat: [PAYCLOUD-473] Init iac

src/idpay/apim/api/idpay_merchants_portal/get-pos-transactions-progress-policy.xml.tpl
=> chore: [EBE-159] change path for policy

src/idpay/apim/api/idpay_appio_full/openapi.appio.full.yml, src/idpay/apim/api/idpay_onboarding_workflow/get-initiative-details-policy.xml.tpl, src/idpay/apim/api/idpay_onboarding_workflow/openapi.onboarding.yml, src/idpay/apim/api/idpay_onboarding_workflow/openapi.onboarding.yml.tpl
=> feat: [UPBE-127] inserimento policy onboarding detail

src/idpay/apim/api/idpay_asset_register/openapi.register.yml
=> feat: [RDB-274] adding model and brand to products api filter and sort

src/idpay/21_apim_api_portal_users.tf, src/idpay/apim/api/idpay_appio_full/openapi.appio.full.yml, src/idpay/apim/api/idpay_payment_io/get-generate-pdf-barcode-web-policy.xml.tpl, src/idpay/apim/api/idpay_payment_io/openapi.payment_io.yml.tpl, src/idpay/apim/api/idpay_timeline/get-timeline-detail-web-policy.xml.tpl
Add endpoint for download report
Add endpoint for timeline operation detail
Add endpoint for download report
Add endpoint for timeline operation detail
---
=> feat: [UPBE-218] added generate transaction PDF API

src/idpay/10_apim_fragments.tf, src/idpay/apim/api/idpay_assistance/get-beneficiary-iban.xml.tpl, src/idpay/apim/api/idpay_assistance/get-beneficiary-instruments.xml.tpl, src/idpay/apim/api/idpay_assistance/get-beneficiary-onboarding-family-status.xml.tpl, src/idpay/apim/api/idpay_assistance/get-beneficiary-onboarding-status.xml.tpl, src/idpay/apim/api/idpay_assistance/get-beneficiary-timeline-detail.xml.tpl, src/idpay/apim/api/idpay_assistance/get-beneficiary-timeline.xml.tpl, src/idpay/apim/api/idpay_assistance/get-beneficiary-wallet.xml.tpl, src/idpay/apim/api/idpay_initiative/get-beneficiary-iban.xml.tpl, src/idpay/apim/api/idpay_initiative/get-beneficiary-instruments.xml.tpl, src/idpay/apim/api/idpay_initiative/get-beneficiary-onboarding-family-status.xml.tpl, src/idpay/apim/api/idpay_initiative/get-beneficiary-onboarding-status.xml.tpl, src/idpay/apim/api/idpay_initiative/get-beneficiary-timeline-detail.xml.tpl, src/idpay/apim/api/idpay_initiative/get-beneficiary-timeline.xml.tpl, src/idpay/apim/api/idpay_initiative/get-beneficiary-wallet.xml.tpl, src/idpay/apim/api/idpay_initiative/put-initiative-readmission-discount.xml.tpl, src/idpay/apim/api/idpay_initiative/put-initiative-readmission-refund.xml.tpl, src/idpay/apim/api/idpay_initiative/put-initiative-suspension-discount.xml.tpl, src/idpay/apim/api/idpay_initiative/put-initiative-suspension-refund.xml.tpl, src/idpay/apim/api_fragment/datavault-tokenizer.xml, src/idpay/apim/api_product/app_io/policy_io.xml.tpl, src/idpay/apim/api_product/app_issuer/policy_issuer.xml.tpl, src/idpay/apim/api_product/mil_api/policy_mil_citizen.xml, src/idpay/apim/api_product/portal_users_api/policy_users_portal.xml.tpl
This PR proposes to create a new fragment for datavault and remove the unused pdv fragment
---
=> fix: Rename datavault fragment and policies

src/idpay/20_apim_api_register.tf, src/idpay/apim/api/idpay_asset_register/openapi.register.yml
=> fix: Rdb 306 modify formal motivation

src/idpay/apim/api/idpay_merchants_op_portal/openapi.merchants.op.portal.yml, src/idpay/apim/api/idpay_merchants_portal/openapi.merchants.portal.yml
Updated merchants operator and merchants portal swagger.
---
=> feat: [EBE-224] updated merchants operator and portal swagger

src/idpay/apim/api/idpay_merchants_op_portal/openapi.merchants.op.portal.yml, src/idpay/apim/api/idpay_merchants_portal/openapi.merchants.portal.yml
=> fix: Fix website camelcase

src/idpay/30_apim_diagnostics.tf
=> fix: [LTBE-29] added merchant op module

src/idpay/apim/api/idpay_merchants_op_portal/openapi.merchants.op.portal.yml, src/idpay/apim/api/idpay_merchants_portal/openapi.merchants.portal.yml
Added authorizedAmountCents field in PointOfSaleTransactionProcessedDTO to handle the authorized amount.
Removed header parameters in reversal and reward api.
---
=> feat: [EBE-242] Updated merchants portal and operator swagger

src/idpay/.terraform.lock.hcl, src/idpay/apim/api/idpay_asset_register/openapi.register.yml
=> fix: Rdb-305 add date formal motivation
